### ISSUE TITLE
UNMET PEER DEPENDENCY yo@^1.4.6

### ISSUE THREAD

**Issue by digitalfrood** [tollwerk/generator-tollwerk#38]
When installing the tollwerk generator globally, the package has a dependency issue regarding the yo version:

```
UNMET PEER DEPENDENCY yo@^1.4.6
```

When trying to use the generator, it displays the following:

<details>
<summary>Terminal Log</summary>

```

     _-----_     ╭──────────────────────────╮
    |       |    │   WELCOME! You're using  │
    |--(o)--|    │  the fantastic tollwerk  │
   `---------´   │       TYPO3 project      │
    ( _´U`_ )    │       kickstarter.       │
    /___A___\   /╰──────────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `


OK, we'll begin with installing TYPO3 ...
Error tollwerk

You don’t seem to have a generator with the name “tollwerk:typo3-install” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-tollwerk:typo3-install.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

</details>

**Comment by jkphl** [comment]
@digitalfrood Thanks for reporting! I've already got an idea what might be the problem and I'll take care of it as soon as possible (end of the week). Also, I **very much appreciate** the use of the `<details>` / `<summary>` in your issue description! :)

**Comment by digitalfrood** [comment]
Hey @jkphl,

would love to check out your generator, as I'm just in the process to set up my own frontend workflow for TYPO3 Projects - your work is a huge inspiration. Just noticed that you're also the maintainer of svg-sprite!

I know, you probably got a lot of stuff to do, but I'd really appreciate it, if you'd find some time to help me out with this one. 🚀

**Comment by jkphl** [comment]
@digitalfrood You're right: I'm in the unfortunate situation that I'm totally swamped with tasks and my head is currently about exploding. However, I'll try to look into it later today. Hope I find a quick solution — sorry for the delay!

**Comment by jkphl** [comment]
@digitalfrood Unfortunately, the problem seems to be more complicated than I thought. I'm having the very same problem on a fresh new server (first installs of Node / Yeoman etc.), but it works on my development server. Versions are the same on both machines ... :( I'm afraid I won't be able to solve this today.

Btw as far as I know the message

```
UNMET PEER DEPENDENCY yo@^1.4.6
```
shouldn't do any harm (although I don't know where it comes from to be honest). I guess you're using Yeoman 1.8.5 as well, right?

I'll keep on trying tomorrow.

**Comment by digitalfrood** [comment]
Yup! 1.8.5 on my side as well. I really appreciate your support!

<details>
<summary>Terminal Log</summary>


➜  ~ yo --version
1.8.5

</details>

**Comment by digitalfrood** [comment]
Oh, wait a minute. Could it be, that you just have to update the generator in npm? https://www.npmjs.com/package/generator-tollwerk

It's 2 years old.

**Comment by jkphl** [comment]
@digitalfrood Oh wow, crazy! Fun fact: It wasn't even me who published the generator on NPM — and I wasn't even aware of that! This might well be the reason for your (and my) issues. However, I have no idea if am able at all to push a new release then. :/

As a short term solution, you could look into whether there's a solution to install a Node module from Github directly (I'm pretty sure this works somehow, maybe just try `npm install -g tollwerk/generator-tollwerk`?)

**Comment by digitalfrood** [comment]
Awesome, it works when using `npm install -g tollwerk/generator-tollwerk`! You could try to contact the maintainer on npm, by visiting his profile here https://www.npmjs.com/~kalypso63

**Comment by jkphl** [comment]
Phew! Happy we got this sorted out. I'll contact him — might be better to give me the ownership of the package (if possible somehow)

**Comment by jkphl** [comment]
@kalypso63 Would you be willing to transfer the ownership of [the NPM package](https://www.npmjs.com/package/generator-tollwerk) over to me? I could take care of publishing new releases whenever I modify the generator sources ... I've never messed around with NMP package owners, but according to [the npm-owner documentation](https://docs.npmjs.com/cli/owner) a simple

```
npm owner add jkphl generator-tollwerk
```

should likely do the trick. **Thank you!**

**Comment by kalypso63** [comment]
It's done. You're unique owner now.

2017-04-30 20:43 GMT+02:00 Joschi Kuphal <notifications@github.com>:

**Comment by jkphl** [comment]
@kalypso63 Awesome, thanks a lot! I'll push out a new release asap! :)

**Comment by jkphl** [comment]
@digitalfrood I just published a 2.0.1 release on npmjs.org. You should be able to remove the Github dependency now if you want.

**Comment by digitalfrood** [comment]
Nice. It's the right Version in my end now, but the peer dependency issue is still there.. kinda:

<details>
<summary>Console Log</summary>

```
fgaa@F ➜  ~  yo
? 'Allo Florian! What would you like to do? Update your generators
? Generators to update generator-tollwerk
/opt/nodes/6.9.1/lib
├── generator-tollwerk@2.0.1
└── UNMET PEER DEPENDENCY yo@^1.8.5

npm WARN generator-tollwerk@2.0.1 requires a peer of yo@^1.8.5 but none was installed.
```

</details>

But it could be just another caching error on my side. Besides of this, its working fine and as expected! Thanks so much for your time!

**Comment by jkphl** [comment]
@digitalfrood I'm not totally sure but I think you can safely ignore this warning. The generator indicates that it's expecting Yeoman to be installed, but as Yeoman is listed as `peerDependency` it won't be installed automatically (it's your responsibility to ensure Yeoman is in place). As you installed Yeoman globally, it won't be found in the `node_modules` folder, which is why the warning is issued. However, as long as Yeoman is there at all everything should be fine. At least this is my interpretation of the issue.

**Comment by digitalfrood** [comment]
Learning something new every day. I think your interpretation is about as close as it gets. Really looking forward to work with your generator now! 🎉 🚀
